
# GET All
GET http://localhost:8686/api/v1/categories HTTP/1.1

###


# GET by ID
GET http://localhost:8686/api/v1/categories/6479a41c09802478c6472bb2 HTTP/1.1

###

# Create new Category

POST http://localhost:8686/api/v1/categories HTTP/1.1
content-type: application/json

{   
    
 "name": "Samsung",
  "description": "Description for Samsung",
  "image": "https://picsum.photos/200/200",
}

### 

# Update Category

PUT http://localhost:8686/api/v1/categories/64795152233756f3b6557996 HTTP/1.1
content-type: application/json

{   
    "name": "Apple",
}

###
DELETE  http://localhost:8686/api/v1/categories/64795152233756f3b6557996 HTTP/1.1
