
# GET All
GET http://localhost:8686/api/v1/users HTTP/1.1

###

# GET by ID
GET http://localhost:8686/api/v1/users/1 HTTP/1.1

###

# Create new User

POST http://localhost:8686/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImVtYWlsIjoidXBhZHRlc0BnbWFpbC5jb20iLCJpYXQiOjE2OTI5MzM5OTd9.eU7mYxQxkNJZfpIRS0S2O2fariE7fZOswJeT7vnW29M

{   
  "lastName": "Davolio 2",
  "firstName": "Nancy",
  "birthDay": "1968-12-08",
  "photo": "EmpID1.pic",
  "email": "nancyes@example.com",
  "phoneNumber": "1234567899",
  "password": "12345678"
}

### 

# Update User

PUT http://localhost:8686/api/v1/users/84 HTTP/1.1
content-type: application/json

{   
  "lastName": "Davolio 4",
  "firstName": "Nancy",
  "birthDay": "1968-12-08",
  "photo": "EmpID1.pic",
  "email": "nancyes@example.com",
  "phoneNumber": "1234567899",
  "password": "123456"
}
###
# Update User Token

PUT http://localhost:8686/api/v1/users/84 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImVtYWlsIjoidXBhZHRlc0BnbWFpbC5jb20iLCJpYXQiOjE2OTI5MzM5OTd9.eU7mYxQxkNJZfpIRS0S2O2fariE7fZOswJeT7vnW29M

{   
  "lastName": "Davolio 4",
  "firstName": "Nancy",
  "birthDay": "1968-12-08",
  "photo": "EmpID1.pic",
  "email": "nancyes@example.com",
  "phoneNumber": "1234567899",
  "password": "123456"
}


###
DELETE  http://localhost:8686/api/v1/users HTTP/1.1
content-type: application/json

{
  "id": 72
}


