# get ALl categories
GET http://localhost:8080/api/v1/categories


### get Single category
http://localhost:8080/api/v1/categories/4

### Update cattegory

PUT http://localhost:8080/api/v1/categories/4
Content-Type: application/json

{
    "name": "Iphone"
}

### 3 dấu 3 để ngăn cách các requests

# Xoa category
DELETE http://localhost:8080/api/v1/categories/4

### POST Them moi
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
    "category_name": "Dien thoai v1",
    "description": "Laptop gia re nhat thanh pho da nang",
    "slug": "dien-thoai"
}
