@baseUrl=http://localhost:8080

### List
GET {{baseUrl}}/api/v1/categories

### Find By ID
GET {{baseUrl}}/api/v1/categories/68fb7ab3dbbe0847aa5ecae4


### Find By ID with invalid id
GET {{baseUrl}}/api/v1/categories/68fb7ab3dbbe0847aa5ecae4


### Create new 
POST {{baseUrl}}/api/v1/categories
Content-Type: application/json

{
    "category_name": "Accessories",
    "slug": "accessories",
    "description": "Mobile accessories"
}

### Create new  with invalid data
POST {{baseUrl}}/api/v1/categories
Content-Type: application/json

{
    "category_name": "Tablet",
    "slug": "tablet"
}

### Update
PUT {{baseUrl}}/api/v1/categories/2
Content-Type: application/json

{
    "description": "Tablet v2 co ban tra gop, gia tot nhat thi truong."
}

### Update with invalid data
PUT {{baseUrl}}/api/v1/categories/68fb79ceca81b40b9e816436
Content-Type: application/json

{
   "category_name": "Laptop Apple v1"
}

### DELETE
DELETE  {{baseUrl}}/api/v1/categories/2
####
