

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};
// This is a client component, 
// which means it will be rendered on the client side.
const AboutPage = () => {
  console.log('This is the About Page');
  return (
    <div>About Page</div>
  )
}

export default AboutPage