PUT http://localhost:8080/api/v1/brands/2
Content-Type: application/json


{
    "name": "Giant update",
    "description": "Road bike description"

}

### Create a new category

POST  http://localhost:8080/api/v1/brands
Content-Type: application/json

{
    "id": 2,
    "name": "Giant",
    "description": "Specializing in road and mountain bikes"
}

### Delete
DELETE http://localhost:8080/api/v1/brands/4
