### GET ALls
GET http://localhost:8080/api/v1/categories

### Update

PUT http://localhost:8080/api/v1/categories/65f19ad11f0317396c586dcc
Content-Type: application/json

{
    "categoryName": "Road bike",
    "description": "Road bike description"

}

### Create a new category

POST  http://localhost:8080/api/v1/categories
Content-Type: application/json

{
    "categoryName": "Hybrid",
    "description": "Versatile bikes for various terrains",
    "slug": "hybrid"
}

### Delete
DELETE http://localhost:8080/api/v1/categories/65f19d7fcd2c7838ae158868
