@baseUrl = http://localhost:8080/api/v1

### get 5 products have promition for home page
GET {{baseUrl}}/products/home/promotions?limit=5
###

### get all products

GET {{baseUrl}}/products?keyword=Granite
###

### Get product by ID
GET {{baseUrl}}/products/:id

###

### Create a new product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "product_name": "Laptop 1",
  "price": 1000,
  "discount": 10,
  "category": "6a0703e8004b0464d96393d9",
  "brand": "6a0703e8004b0464d96393d5",
  "description": "A laptop for everyday use",
  "model_year": 2022,
  "slug": "laptop",
  "thumbnail": "https://example.com/laptop.jpg",
  "stock": -5
}

###

### Update a product by ID
PUT {{baseUrl}}/products/:id
Content-Type: application/json

{
  "product_name": "Laptop",
  "price": 1000,
  "discount": 10,
  "category": "Electronics",
  "brand": "Dell",
  "description": "A laptop for everyday use",
  "model_year": 2022,
  "slug": "laptop",
  "thumbnail": "https://example.com/laptop.jpg",
  "stock": 10
}

###

### Delete a product by ID
DELETE {{baseUrl}}/products/:id
