import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function  Home() {
  console.log('This is the Home Page');
 

  
  return (
    <main className="flex grow items-center justify-center p-4">
    <h1 className="text-3xl font-bold underline">Hello world!</h1>
        </main>
  );
}
