
# Create a category
POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmQ4NDdiMTE4OTk3NTE4MzA5NjE5MTMiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3MjU0NTE3MzMsImV4cCI6MTcyNjA1NjUzM30.Qklf-Y_u0RP3DZ-TpAdBhG5KY9TXs-l9NzRDhgUWbLY

{
    "customer": {
      "first_name": "John",
      "last_name": "Henry",
      "phone": "09888777666",
      "email": "nhannn87dn@gmail.com",
      "street": "24 le thanh ton",
      "city": "hai chau",
      "state": "da nang"
    },
    "payment_type": 1,
    "order_note": "goi truoc khi giao",
    "order_items": [
        {
            "product": "67b477ac754d958ca4f321cb",
            "price":846.35,
            "discount": 42,
            "quantity": 1
        }
    ]
}


###


# Create a category
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
    "customer": {
      "first_name": "John",
      "last_name": "Henry",
      "phone": "1234567896",
      "email": "nhannn87dn@gmail.com",
      "street": "1600 yen bai",
      "city": "hai chau",
      "state": "da nang"
    },
    "payment_type": 1,
    "order_note": "goi truoc khi giao",
    "order_items": [
        {
            "product": "66acd7a86977747d54d18456",
            "price": 883,
            "discount": 0,
            "quantity": 1
        }
    ]
}


