### create
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "product_name": "Sample Product 2",
  "price": 100,
  "discount": 10,
  "description": "This is a sample product description.",
  "model_year": 2023,
  "stock": 50,
  "slug": "sample-product-2",
  "thumbnail": "http://example.com/sample-thumbnail.jpg",
  "category": "67b476518bf53c888a7d9252", 
  "brand_id": "67b474bacfb39df410e04918",
  "alibaba": "40 ten cuop"
}


### updatte
PUT http://localhost:8080/api/v1/products/67b7171dc2363f3c1a6f709a
Content-Type: application/json

{
  "product_name": "Sample Product 222",
  "alibaba": "40 ten cuop"
}


### updatte
DELETE  http://localhost:8080/api/v1/products/67b7171dc2363f3c1a6f709a


### Get ALl
GET http://localhost:8080/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2MwNGM1ZTU1NTg4ODU2MDQwMzgxMzUiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc0MjA0NDYxMiwiZXhwIjoxNzQyMTMxMDEyfQ.mGcFB7YLbB_tjG61evo4QSnUdhvGia5J_CaRHzHi6jA

### Get ALl
GET http://localhost:8080/api/v1/products/67b477ac754d958ca4f321d5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2MwNGM1ZTU1NTg4ODU2MDQwMzgxMzUiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc0MTY5MjA0NywiZXhwIjoxNzQxNzc4NDQ3fQ.ZOrfqy2tc99WUgLQIa2aTgQfrqFwPSJXrdMexdDCWYM
