POST http://localhost:9000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "CatFly@200miles"
}

###

POST http://localhost:9000/api/v1/auth/login
Content-Type: application/json

{
    "email": "dev@gmail.com",
  "password": "CatFly@200miles"
}

###
POST http://localhost:9000/api/v1/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4N2Y4YmYyYTM3NmU3OTliMDM4YzAyMCIsImVtYWlsIjoiZGV2QGdtYWlsLmNvbSIsImlhdCI6MTc1MzM1OTE4MSwiZXhwIjoxNzU1OTUxMTgxfQ.F5440RHQNGbjUmHtvA26SDNAlqFXpQySr9r785RDniU


### Get Profile
GET http://localhost:9000/api/v1/auth/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4N2Y4NWRhYmRmZTNjNDdmNjJiZmJhYSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZXMiOlsic3RhZmYiXSwiaWF0IjoxNzU0Mzk4NDY3LCJleHAiOjE3NTQ0MDIwNjd9.ZTJsV9NW9UmkpfUVGwQUWdLX6LeyME7kQym2BNtkmaI