POST http://localhost:9000/api/v1/categories
Content-Type: application/json

{
  "category_name": "Laptop",
  "description": "All about laptops",
  "slug": "laptop"
}

###
GET http://localhost:9000/api/v1/categories
x-api-key: l5YvVVbedh6qeqRELX0UcCftgRHwVrT7
###

PUT http://localhost:9000/api/v1/categories/6878f0835d5016b5abe1c90b
Content-Type: application/json

{
  "description": "All about laptops updated v2"
}

###
DELETE http://localhost:9000/api/v1/categories/6878f0835d5016b5abe1c90b