GET http://localhost:9000/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4N2Y4NWRhYmRmZTNjNDdmNjJiZmJhYSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZXMiOlsic3RhZmYiXSwiaWF0IjoxNzU0Mzk2MzI1LCJleHAiOjE3NTQzOTk5MjV9.ego5jdJO8bwzIh6zyVtYqVGf_h6vxao8oP7yOX4CX54