### GET ALL
GET http://localhost:8080/api/v1/categories


### GET One
GET http://localhost:8080/api/v1/categories/2

### create
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "category_name": "Nin"
}

### uPDATE
PUT http://localhost:8080/api/v1/categories/67bdb143ddb8d7647c671e56
Content-Type: application/json

{
  "category_name": "Non"
}