### create
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "product_name": "Sample Product 2",
  "price": 100,
  "discount": 10,
  "description": "This is a sample product description.",
  "model_year": 2023,
  "stock": 50,
  "slug": "sample-product-2",
  "thumbnail": "http://example.com/sample-thumbnail.jpg",
  "category": 2, 
  "brand": 1
}


### updatte
PUT http://localhost:8080/api/v1/products/2
Content-Type: application/json

{
  "stock": 10
}


### updatte
DELETE  http://localhost:8080/api/v1/products/2
