# GET All
GET http://localhost:8080/api/v1/categories

###

# Get Single
GET http://localhost:8080/api/v1/categories/4


###

# Create a category
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "category_name": "      Tablet v3    ",
  "description": "Tablet v2 gia re da nang",
  "slug": "tablet-v3"
}



###

# Update a category
PUT http://localhost:8080/api/v1/categories/66aa378c9f92ff21f2d09246
Content-Type: application/json

{
  "category_name": "Tablet v2",
  "slug": "tablet-v2"
}


### 
# Delete Category
DELETE  http://localhost:8080/api/v1/categories/66aa2e47c5531e76fb8d3152