POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
    "product_name": "tên sản phẩm test 2",
    "price": 200.0,
    "discount": 3,
    "category": "66acd7a76977747d54d1843d",
    "brandId": "66acd7a76977747d54d1844c",
    "model_year": 2024,
    "description": "mô tả sản phẩm",
    "thumbnail": "https://picsum.photos/400/400",
    "stock": 10
    
}

###

# update

PUT http://localhost:8080/api/v1/products/66b0d40ae6cad4e762c4d200
Content-Type: application/json

{
    "product_name": "tên sản phẩm test 4",
    "price": 400.0
}


###

# delete

DELETE  http://localhost:8080/api/v1/products/66b0d40ae6cad4e762c4d002
