PUT https://api.escuelajs.co/api/v1/products/393
Content-Type: application/json

{
  "title": "Change title v2"
}

### create

POST https://api.escuelajs.co/api/v1/products/
Content-Type: application/json

{
  "title": "New Product 11",
  "price": 10,
  "description": "A description",
  "categoryId": 228,
  "images": ["https://placeimg.com/640/480/any"]
}