# Lấy danh sách students
GET http://localhost:8000/api/v1/students

### get single student
GET http://localhost:8000/api/v1/students/1


### create new student
POST http://localhost:8000/api/v1/students
Content-Type: application/json

{
  "name": "Clark Kent",
  "age": 18,
  "email": "clark.kent@example.com"
}

### Update student
PUT http://localhost:8000/api/v1/students/3
Content-Type: application/json

{
  "age": 21
}

### Delete student
DELETE http://localhost:8000/api/v1/students/3