# Lấy danh sách students
GET http://localhost:8000/api/v1/students?page=1&limit=10&sortBy=name&sortOrder=asc

### get single student
GET http://localhost:8000/api/v1/students/abc


### create new student
POST http://localhost:8000/api/v1/students
Content-Type: application/json

{
  "name": "abc",
  "age": 18,
  "email": "clark.kent2@example.com"
}

### Update student
PUT http://localhost:8000/api/v1/students/1
Content-Type: application/json

{
  "age": 21
}

### Delete student
DELETE http://localhost:8000/api/v1/students/3