#@baseUrl = https://learn-backend-nodejs.onrender.com
@baseUrl = http://localhost:9000

### Get all brands
GET  {{baseUrl}}/api/v1/brands

### Get brand by id
GET {{baseUrl}}/api/v1/brands/1

### Create brand
POST {{baseUrl}}/api/v1/brands
content-type: application/json

{
    "brand_name": "Brand 6",
    "description": "Description 6",
    "slug": "brand-6"
}

### Update brand
PUT {{baseUrl}}/api/v1/brands/6
content-type: application/json

{
    "brand_name": "Brand 16"
}

### Delete brand
DELETE {{baseUrl}}/api/v1/brands/1