
## Creat a Supplier
POST http://localhost:8080/api/v2/employees HTTP/1.1
content-type: application/json

{
  "firstName": "Nguyen Ngoc",
  "lastName": "Nhan",
  "email": "nhan@gmail.com",
  "phoneNumber": "133777665",
  "address": "90 Tran Tong",
  "birthDay": "2000-12-12",
  "password": "Catfly200miles",
  "photo": "https://avatars.githubusercontent.com/u/97165289"
}
