
GET http://localhost:8080/api/v1/users/6482d04ecfe5b4e115b18d27 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgyZDA0ZWNmZTViNGUxMTViMThkMjciLCJlbWFpbCI6InJvb3RAZXhhbXBsZS5jb20iLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsImlhdCI6MTY5NjQ5NTYzMn0.p-Co5b1LK5W3SWk4I_Qw3xqpBgSaOnQ4gtQhRvEOl6Y

###

GET http://localhost:8080/api/v1/employees HTTP/1.1

###

POST http://localhost:8080/api/v1/employees HTTP/1.1
content-type: application/json

{
      "firstName": "Ngoc Ho",
      "lastName": "Nguyen Nhan",
      "email": "ngocnhan@gmail.com",
      "phoneNumber": "0988071443",
      "address": "3121 Spinka Points",
      "photo": "",
      "birthday": "2024-06-28T06:18:11.141Z",
      "password": "Ngocnhan87dn123"
    }