# Cấu hình domain chung
@baseUrl=http://localhost:9000

# get categories
GET {{baseUrl}}/api/v1/categories


###
GET {{baseUrl}}/api/v2/categories
###

# get category by id
GET {{baseUrl}}/api/v1/categories/1

### create new a category
POST {{baseUrl}}/api/v1/categories
Content-Type: application/json

{
    "name": "Accessories",
    "description": "Accessories gia re"
}


### Update by ID
PUT {{baseUrl}}/api/v1/categories/3
Content-Type: application/json

{
    "name": "Watch"
}


### Delete by ID
DELETE  {{baseUrl}}/api/v1/categories/4
