# Cấu hình domain chung
@baseUrl=http://localhost:9000
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTc0ODA3MDI4NWE4ZTVmNDU0ZTEzNTgiLCJyb2xlIjoic3RhZmYiLCJlbWFpbCI6InN0YWZmMUBleGFtcGxlLmNvbSIsIm5hbWUiOiJOZ3V5ZW4gVmFuIEEiLCJpYXQiOjE3ODcwNTg0MzIsImV4cCI6MTc4NzA2MjAzMn0.Hk8EGyA9_LbReleAt8RKAP138p35jn496LytMjN-4EY
# get products
GET {{baseUrl}}/api/v1/products?page=1&limit=10
Authorization: Bearer {{accessToken}}
###

# get product by id
GET {{baseUrl}}/api/v1/products/6a71cbde6d01c903b1348700

### create new a product
POST {{baseUrl}}/api/v1/products
Content-Type: application/json

{
	"product_name": "Iphone 19 64GB",
	"description": "Iphone 19 64GB gia re",
	"price": 9000,
	"model_year": 2029,
	"category": "6a6dd690b74b5aeea306dd70",
	"brand": "6a6dd83f24d3bcd55ff21c7f"
}


### Update by ID
PUT {{baseUrl}}/api/v1/products/6a71cd96a1ed8d94625238c0
Content-Type: application/json

{
	"model_year": 2019
}


### Delete by ID
DELETE  {{baseUrl}}/api/v1/products/6a71cbde6d01c903b1348762
