@baseUrl = http://localhost:8080

### create new product
POST {{baseUrl}}/api/v1/products
Content-Type: application/json

{
    "product_name": "Sample Product",
    "slug": "sample-product",
    "description": "This is a sample product.",
    "price": 29.99,
    "category": 1, 
    "brand": 1,
    "model_year": 2023,
    "stock": 100
}

### Update
PUT {{baseUrl}}/api/v1/products/697c99212d5eb0ca72e5c257
Content-Type: application/json

{
    "isNew": true
}